server:
  port: 8083
spring:
  datasource:
    url: jdbc:sqlserver://LAPTOP-SJOHHLS5;databaseName=prueba_examen
    username: mike
    password: mike
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
